// <auto-generated />
using System;
using BanterBotSports.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BanterBotSports.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327195702_AddLogoUrlsToPartido")]
    partial class AddLogoUrlsToPartido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanterBotSports.DAL.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreDisplay")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BanterBotSports.Entities.ConfiguracionPremio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("ConfiguracionesPremio");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Jornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Jornadas");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId", "UserId")
                        .IsUnique();

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipo1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipo2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<int?>("GolesEquipo1Oficial")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesEquipo2Oficial")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesReglamento")
                        .HasColumnType("integer");

                    b.Property<int>("JornadaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("KickOffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrlLocal")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrlVisitante")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JornadaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("BanterBotSports.Entities.PrediccionJornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GolesPronosticados")
                        .HasColumnType("integer");

                    b.Property<int>("JornadaId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosObtenidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("JornadaId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("PrediccionesJornada");
                });

            modelBuilder.Entity("BanterBotSports.Entities.PrediccionPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Fuente")
                        .HasColumnType("integer");

                    b.Property<int>("GolesEquipo1")
                        .HasColumnType("integer");

                    b.Property<int>("GolesEquipo2")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosObtenidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("PartidoId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("PrediccionesPartido");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoInscripcion")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumJornadas")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizadorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PtosGolesJornada")
                        .HasColumnType("integer");

                    b.Property<int>("PtosMarcador")
                        .HasColumnType("integer");

                    b.Property<int>("PtosResultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("BanterBotSports.Entities.UsuarioTelegram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("UsuariosTelegram");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BanterBotSports.Entities.ConfiguracionPremio", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Torneo", "Torneo")
                        .WithMany("ConfiguracionPremios")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Jornada", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Torneo", "Torneo")
                        .WithMany("Jornadas")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Participante", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Torneo", "Torneo")
                        .WithMany("Participantes")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Partido", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Jornada", "Jornada")
                        .WithMany("Partidos")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("BanterBotSports.Entities.PrediccionJornada", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Jornada", "Jornada")
                        .WithMany("PrediccionesJornada")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterBotSports.Entities.Participante", "Participante")
                        .WithMany("PrediccionesJornada")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jornada");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("BanterBotSports.Entities.PrediccionPartido", b =>
                {
                    b.HasOne("BanterBotSports.Entities.Participante", "Participante")
                        .WithMany("PrediccionesPartido")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterBotSports.Entities.Partido", "Partido")
                        .WithMany("PrediccionesPartido")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BanterBotSports.DAL.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BanterBotSports.DAL.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterBotSports.DAL.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BanterBotSports.DAL.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BanterBotSports.Entities.Jornada", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("PrediccionesJornada");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Participante", b =>
                {
                    b.Navigation("PrediccionesJornada");

                    b.Navigation("PrediccionesPartido");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Partido", b =>
                {
                    b.Navigation("PrediccionesPartido");
                });

            modelBuilder.Entity("BanterBotSports.Entities.Torneo", b =>
                {
                    b.Navigation("ConfiguracionPremios");

                    b.Navigation("Jornadas");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
